module

public import Noperts.Stellated.FlipPolysBase

@[expose] public section

/-! Flip polynomial data for the flip leaves of the corner tables (generated by
`kernelCorner flippolys`). -/

namespace Noperts.Stellated.CornerKernel

open CornerPoly CornerTree SparsePoly FlipPrune

set_option maxHeartbeats 0
set_option linter.unusedSimpArgs false
set_option maxRecDepth 100000

def flipFP0 : FactPoly := ⟨[([0, 1, 0, 0, 1], 324, false), ([0, 1, 1, 0, 0, 1], 324, true), ([0, 1, 1, 0, 1], 792, false), ([0, 2], 81, true), ([0, 2, 2], 162, true), ([1, 2, 0, 0, 1], 162, true), ([1, 2, 1, 0, 0, 1], 162, false), ([1, 2, 1, 0, 1], 396, true), ([2, 2, 0, 0, 2], 162, false), ([2, 2, 1, 0, 1, 1], 324, true), ([2, 2, 1, 0, 2], 792, false), ([2, 2, 2, 0, 0, 2], 162, false), ([2, 2, 2, 0, 1, 1], 792, true), ([2, 2, 2, 0, 2], 968, false)], [2], 162⟩

theorem flipFP0_ok : FlipOk flipFP0 true .skew 4 := by
  refine ⟨by decide, by decide, fun y => ?_⟩
  simp only [flipFP0, toIPoly, IPoly.toPoly, List.map, eval_cons, eval_nil, sgnI]
  simp only [flipPoly, flipLin, xPolyK, eval_add, eval_mul, eval_scale, eval_const, eval_wPoly, wVal]
  simp [flipCoeff, B0, F1, F2, sVal, tVal, monoEval, monoEvalFrom, eval_var, xPoly, eval_add,
    eval_mul, eval_scale, eval_const, sPoly, tPoly, M1, M2, M3, scalePoly, eval_scalePoly, scaleVal,
    skewK, atubeA, plainX, skewX, tubeX]
  ring

def flipFP1 : FactPoly := ⟨[([0, 1, 0, 0, 1], 4, false), ([0, 1, 1, 0, 0, 1], 4, true), ([0, 2], 1, true), ([0, 2, 2], 2, true), ([1, 2, 0, 0, 1], 2, true), ([1, 2, 1, 0, 0, 1], 2, false), ([2, 2, 0, 0, 2], 2, false), ([2, 2, 1, 0, 1, 1], 4, true), ([2, 2, 2, 0, 0, 2], 2, false)], [2], 2⟩

theorem flipFP1_ok : FlipOk flipFP1 true .plain 4 := by
  refine ⟨by decide, by decide, fun y => ?_⟩
  simp only [flipFP1, toIPoly, IPoly.toPoly, List.map, eval_cons, eval_nil, sgnI]
  simp only [flipPoly, flipLin, xPolyK, eval_add, eval_mul, eval_scale, eval_const, eval_wPoly, wVal]
  simp [flipCoeff, B0, F1, F2, sVal, tVal, monoEval, monoEvalFrom, eval_var, xPoly, eval_add,
    eval_mul, eval_scale, eval_const, sPoly, tPoly, M1, M2, M3, scalePoly, eval_scalePoly, scaleVal,
    skewK, atubeA, plainX, skewX, tubeX]
  ring

def flipFP2 : FactPoly := ⟨[([0, 1, 0, 0, 1], 4, false), ([0, 1, 1, 0, 0, 1], 4, true), ([0, 2], 1, true), ([0, 2, 2], 2, true), ([1, 2, 0, 0, 1], 2, true), ([1, 2, 1, 0, 0, 1], 2, false), ([2, 2, 0, 0, 2], 2, false), ([2, 2, 1, 0, 1, 1], 4, true), ([2, 2, 2, 0, 0, 2], 2, false)], [2], 2⟩

theorem flipFP2_ok : FlipOk flipFP2 true .aplain 4 := by
  refine ⟨by decide, by decide, fun y => ?_⟩
  simp only [flipFP2, toIPoly, IPoly.toPoly, List.map, eval_cons, eval_nil, sgnI]
  simp only [flipPoly, flipLin, xPolyK, eval_add, eval_mul, eval_scale, eval_const, eval_wPoly, wVal]
  simp [flipCoeff, B0, F1, F2, sVal, tVal, monoEval, monoEvalFrom, eval_var, xPoly, eval_add,
    eval_mul, eval_scale, eval_const, sPoly, tPoly, M1, M2, M3, scalePoly, eval_scalePoly, scaleVal,
    skewK, atubeA, plainX, skewX, tubeX]
  ring

def flipFP3 : FactPoly := ⟨[([0, 1, 0, 0, 0, 1], 4, true), ([0, 1, 1, 0, 1], 4, false), ([0, 2], 2, true), ([0, 2, 2], 1, true), ([1, 2, 1, 0, 0, 1], 2, false), ([1, 2, 2, 0, 1], 2, true), ([2, 2, 0, 0, 0, 2], 2, false), ([2, 2, 1, 0, 1, 1], 4, true), ([2, 2, 2, 0, 2], 2, false)], [2], 2⟩

theorem flipFP3_ok : FlipOk flipFP3 false .plain 4 := by
  refine ⟨by decide, by decide, fun y => ?_⟩
  simp only [flipFP3, toIPoly, IPoly.toPoly, List.map, eval_cons, eval_nil, sgnI]
  simp only [flipPoly, flipLin, xPolyK, eval_add, eval_mul, eval_scale, eval_const, eval_wPoly, wVal]
  simp [flipCoeff, B0, F1, F2, sVal, tVal, monoEval, monoEvalFrom, eval_var, xPoly, eval_add,
    eval_mul, eval_scale, eval_const, sPoly, tPoly, M1, M2, M3, scalePoly, eval_scalePoly, scaleVal,
    skewK, atubeA, plainX, skewX, tubeX]
  ring

def flipFP4 : FactPoly := ⟨[([0, 1, 0, 0, 1], 324, false), ([0, 1, 1, 0, 0, 1], 324, true), ([0, 1, 1, 0, 1], 792, false), ([0, 2], 81, true), ([0, 2, 2], 162, true), ([1, 2, 0, 0, 1], 162, true), ([1, 2, 1, 0, 0, 1], 162, false), ([1, 2, 1, 0, 1], 396, true), ([2, 2, 0, 0, 2], 162, false), ([2, 2, 1, 0, 1, 1], 324, true), ([2, 2, 1, 0, 2], 792, false), ([2, 2, 2, 0, 0, 2], 162, false), ([2, 2, 2, 0, 1, 1], 792, true), ([2, 2, 2, 0, 2], 968, false)], [2], 162⟩

theorem flipFP4_ok : FlipOk flipFP4 true .askew 4 := by
  refine ⟨by decide, by decide, fun y => ?_⟩
  simp only [flipFP4, toIPoly, IPoly.toPoly, List.map, eval_cons, eval_nil, sgnI]
  simp only [flipPoly, flipLin, xPolyK, eval_add, eval_mul, eval_scale, eval_const, eval_wPoly, wVal]
  simp [flipCoeff, B0, F1, F2, sVal, tVal, monoEval, monoEvalFrom, eval_var, xPoly, eval_add,
    eval_mul, eval_scale, eval_const, sPoly, tPoly, M1, M2, M3, scalePoly, eval_scalePoly, scaleVal,
    skewK, atubeA, plainX, skewX, tubeX]
  ring

def flipFP (seg : Bool) (kind : ChartKind) (k : Fin 12) : Option FactPoly :=
  if seg = true ∧ kind = .askew ∧ k = 4 then some flipFP4 else
    if seg = false ∧ kind = .plain ∧ k = 4 then some flipFP3 else
    if seg = true ∧ kind = .aplain ∧ k = 4 then some flipFP2 else
    if seg = true ∧ kind = .plain ∧ k = 4 then some flipFP1 else
    if seg = true ∧ kind = .skew ∧ k = 4 then some flipFP0 else
    none

theorem flipFP_ok {seg : Bool} {kind : ChartKind} {k : Fin 12} {fp : FactPoly}
    (h : flipFP seg kind k = some fp) : FlipOk fp seg kind k := by
  unfold flipFP at h
  split_ifs at h <;> (try simp at h) <;> subst h
  all_goals (obtain ⟨rfl, rfl, rfl⟩ := ‹_›; first | exact flipFP0_ok | exact flipFP1_ok | exact flipFP2_ok | exact flipFP3_ok | exact flipFP4_ok)

end Noperts.Stellated.CornerKernel
